### PR TITLE
Allow ListArchive to fail gracefully

### PR DESCRIPTION
**Pull request by error454**
It's possible for `ListArchive` to fail, for instance, if you try to open an unsupported compression format. In the case of failure, it's nice to have `OnDone` called with a completion state of `FAILURE_UNKNOWN`.

Also updated 7zpp library to bring in fixes to from https://github.com/getnamo/7zip-cpp/pull/24.

### CODE REVIEW

**Comment by getnamo** [comment]
Looks good. Just cleaned up braces for ue4 standard. I don't religiously follow the standard but I do try to keep that part consistent and I've noticed that slips for myself sometimes when writing lambdas...

**Comment by error454** [comment]
> Just cleaned up braces for ue4 standard. 
Thanks for mentioning that. I've been stopping myself from instinctively updating braces and single-line if's because I wasn't sure which standard was desired.

**Comment by getnamo** [comment]
I generally think the ue4 coding standard is sane and reasonable. I think I largely only tend to diverge on the use of ```auto```, I find it very convenient to use it in certain places e.g. https://github.com/getnamo/ZipUtility-ue4/blob/e2e0ae4255177570da287a0f3c64db2e7da41b87/Source/WindowsUtility/Private/WindowsFileUtilityFunctionLibrary.cpp#L96 which I guess would sometimes fit in the iterator exception.

**Comment by error454** [comment]
I just had to do a double-take. The last time I looked at the UE4 coding guidelines, they were *recommending* using `auto` in range based for loops. I had to dig up the commit log to double check my memory: https://github.com/EpicGames/UnrealEngine/commit/2cc738c3b3c13467381c34b1dc66fadd641f0f17#diff-d68de90356270f6bc8937fd177dace14L251

**Pull request merged**
