### PR TITLE
Add support for aborting a zip operation

### PR DESCRIPTION
**Pull request by error454**
Hey, sorry this ended up being a bit of a wrecking ball in the end. Getting the base zip library to support aborting an operation was simple and after doing so I realized that my main performance issue was that I was creating too many in-flight zip operations at a time. This led me down a path of queue'ing and in the end, the best solution seemed to be the addition of a queued thread pool in `WFULambdaRunnable`. 

So long story short, zip operations can now be cancelled and you can also queue up a ton of them safely without killing yourself. Specific change highlights below.

Please leave comments for anything that looks slightly suspicious. Once this PR gets through I'll do a PR for the docs to show BP usage but want to wait in-case we change anything.

One final note, I only submitted an updated 64-bit library, I don't think 32-bit is a valid target for UE4.

### `ProgressCallback.h` 
Was changed to use pure virtual functions to eliminate a compile error on the UE4 library side.

### `SevenZipCallbackHandler` 
Was moved to its own file to allow being referenced by new class `ZipOperation`.

### `ZipFileFunctionLibrary`
* Moved `SevenZipCallbackHandler` out to its own class file.
* Moved `RunLambdaOnGameThread` to the public interface to allow calling from `SevenZipCallbackHandler`'s new location.
* Most zip/unzip operations now return a `UZipOperation` which allows for early cancellation of the operation. This excludes only the `UnzipFileNamed` and `UnzipFileNamedTo` methods... I was too tired to figure out the indirection required to support these. One could still use the new functionality by calling `UnzipFilesTo` directly after manually listing an archive (and incidentally this would be a better way to do things if you're frequently unzipping single files from the same archive since you avoid the overhead of the list operation).
* `UnzipFilesOnBGThreadWithFormat`, `UnzipOnBGThreadWithFormat` and `ZipOnBGThread` now run their lambdas on a queued thread pool
* Fixed minor memory leak in `UnzipFilesOnBGThreadWithFormat`.

### `WFULambdaRunnable`
Did a lot of cleanups here, removing some unused virtual implementations and some unused variables. All of the old `RunLambdaOnBackGroundThread` stuff was kept and still functions exactly the same way, it is still used for List operations because I figured they don't make much sense to cancel.

The primary addition here is of a lazily initialized static `FQueuedThreadPool` where all zip operations that are cancelable are run. The primary entry points for interacting with the queued thread pool are the 3 static functions:
* `InitThreadPool(int32 NumberOfThreads)` this is entirely optional as the thread pool will be lazily initialized the first time that a lambda is queued, the default will be 4 threads if this isn't ran.
* `IQueuedWork* AsyncLambdaPool(...)`
* `bool RemoveLambdaFromQueue(IQueuedWork* Work)`

### `ZipOperation`
A UObject derived class that is now returned from every cancelable zip operation. The only user-facing interface is the `StopOperation()` method, which attempts to stop a zip/unzip operation if it is still valid; first at the thread pool level, then at the sevenzip level.

### CODE REVIEW

**Comment by getnamo** [comment]
Wow this is quite a lot of very appreciated updates :).

Some notes:
- In my personal use cases I never hit performance bottlenecks, but if you're processing a lot of individual unzip/zipping operations I can totally see the benefit of threadpools, awesome addition.
- Lack of 32bit is acceptable. It used to be the case in circa <UE4.5 that all packaged games were 32bit, I don't believe that's true anymore.

Two potential gotchas I can think of after scanning changes:
- UE4 garbage collection generally runs on a 1 min interval, but it can be called unexpectedly. ```UZipOperation``` may need to be rooted ([```ZipOperation->AddToRoot()```](http://api.unrealengine.com/INT/API/Runtime/CoreUObject/UObject/UObjectBaseUtility/AddToRoot/)) to prevent accessing GC memory until it is no longer needed at which point it would be [unrooted](http://api.unrealengine.com/INT/API/Runtime/CoreUObject/UObject/UObjectBaseUtility/RemoveFromRoot/).
- [```AsyncLambdaPool```](https://github.com/error454/ZipUtility-ue4/blob/87a6b9bad91050c3bf92d80a355e0217c1fb354c/Source/WindowsUtility/Public/WFULambdaRunnable.h#L60) may put that file under ue4 license due to it being directly taken from engine code. It's likely ok but may need a note at the top of the file.

**Comment by error454** [comment]
> UE4 garbage collection generally runs on a 1 min interval, but it can be called unexpectedly. UZipOperation may need to be rooted (ZipOperation->AddToRoot()) to prevent accessing GC'd memory, then when it is no longer needed it should be unrooted, probably best spot would be here.

I know that instantiated `UZULambdaDelegate`'s are added to the root set for a good reason, we don't want the lambda to get GC'd before it is finished. The unique case of `UZULambdaDelegate` is that it is never actually stored in any UPROPERTY marked variable to fend off GC. 

I would argue that for the case of `UZipOperation` we actually want it to get GC'd and do not want it in the root set. The way I see it, users of the zip library will take 2 paths with `UZipOperation`:

1. An implementation will use `UZipOperation` by storing the returned pointer so that an operation can be stopped later. In the case of Blueprint, all variables are `UPROPERTY`, so this automatically increments the `UObject` reference counter and prevents GC. In C++, users will have to store the pointer in a `UPROPERTY` marked variable or container like every other pointer they've ever wanted to prevent GC on.

2. An implementation won't care about stopping operations and will completely ignore the returned `UZipOperation`. This is fine since `UZipOperation` is completely non-critical for the completion of the background thread(s). In this case `UZipOperation` will get safely GC'd.

There's no other means of acquiring a `UZipOperation` for a started operation, the user either saves it off when the operation is started or they've missed their chance. So there's no worry of a user trying to acquire a GC'd `UZipOperation` in a retrospective fashion.

I've tested this by enabling the `gc.CollectGarbageEveryFrame` option and as expected `UZipOperation` acts like any other `UObject`. When referenced it sticks around, otherwise it gets GC'd. So the implementation as-is feels like business as usual for a UE4 developer.

> AsyncLambdaPool may put that file under ue4 license due to it being directly taken from engine code. It's likely ok but may need a note at the top of the file.

Since I have a fairly extensive note in the .h itself, were you thinking it would be enough to insert their copyright header at the top of the file? e.g.
`// Copyright 1998-2017 Epic Games, Inc. All Rights Reserved.`

**Comment by getnamo** [comment]
I believe you're are correct on the ```UZipOperation```. Given how it is used and with your testing, it is reasonable to expect a dev to store the UObject if they're interested in this functionality, I may just suggest to add a note in c++ comment above the function about that requirement. If I did a modern rewrite I would probably have changed everything to be one level lower and use smart pointers with raw classes e.g. FLamdaDelgate/etc, but I'm not sure such a rewrite is worth the outcome. Devs using the library still have a very simple and usable UX. I'll go ahead an merge.

On the second (```AsyncLambaPool```) point, ill add the notice after the merge. I think that should be sufficient.

**Comment by getnamo** [comment]
added the notes and comments in what I thought were relevant locations: https://github.com/getnamo/ZipUtility-ue4/commit/fc6c432bee0b56a81aa26efefae4cdfbab7188b2 and https://github.com/getnamo/ZipUtility-ue4/commit/a739e47f4b5b1689cd9e7a5e5bc278b5e45b4866. Should be ready for the documentation pass :)

**Pull request merged**
